"""empty message

Revision ID: d1a0fcc1470a
Revises: 
Create Date: 2019-10-01 23:06:28.097821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a0fcc1470a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('irrigation_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('humidity_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('illumination_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('harvest_notifications_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('notifications_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notifications_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('notifications')
    # ### end Alembic commands ###
